### ISSUE TITLE
聊天列表中数据超过4000条 内存飙升

### ISSUE THREAD

**Issue by wgq4812** [qian-o/Dimension#3]
聊天列表中数据超过4000条  内存会飙升。有解决办法吗？

**Comment by qian-o** [comment]
WPF端嘛？

**Comment by wgq4812** [comment]
对的，大佬 有试过吗？

**Comment by qian-o** [comment]
方便截个图或录下视频嘛？

**Comment by wgq4812** [comment]
聊天列表中 有头像 昵称 时间 新消息提醒 最后一条消息展示  
但是当数据过多之后，内存会直接飙升的很高，

**Comment by qian-o** [comment]
其实这边我考虑的并不足，所有聊天数据都存放到了内存中。
应该将GetChattingRecords接口设置成分页形式或只获取前一百条消息。
![image](https://user-images.githubusercontent.com/84434846/196211344-26fbbf11-bbb9-4e90-ae53-d0c7c95f53fb.png)
![image](https://user-images.githubusercontent.com/84434846/196211459-e31c500e-055c-4b76-b715-8c6c3d895bff.png)

**Comment by qian-o** [comment]
从服务端限制消息数量或在wpf端中sqlite数据库中加入聊天记录类型的表做缓存。

**Comment by wgq4812** [comment]
我们现在在用WPF开发一个聊天工具  我搜索看到了你的作品。感觉挺好的。但是我现在遇到了问题就是 数据量大了之后 头像图片就占用超过内存 。

**Comment by wgq4812** [comment]
我的聊天工具 是以会话的形式为主题 ，有的账号 可能会有10000个会话。 所以直接就炸了。
会话会显示 头像 名称 时间 消息等

**Comment by wgq4812** [comment]
我在去 研究研究 。感谢。

**Comment by qian-o** [comment]
哈哈 好，有问题可以再讨论。
